json_metrics = """
{
	'metrics': [
	{
		'name': 'first_leads',
		'title': 'Новые заявки',
		'info': 'Заявки клиентов, которые ранее не оставляли сделок в вашем бизнесе.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3200,
		'type': 'integer',
		'formula': '{first_leads} ? ({first_leads}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeated_leads',
		'title': 'Повторные заявки',
		'info': 'Количество заявок клиентов, которые уже ранее совершали сделку в вашем бизнесе. Если первая заявка была оставлена до периода отчета, то все новые заявки клиента в периоде отчета будут повторными.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3230,
		'type': 'integer',
		'formula': '{repeated_leads} ? ({repeated_leads}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeated_leads_rate',
		'title': 'Повторные заявки, %',
		'info': 'Доля заявок клиентов, которые уже ранее совершали сделку в вашем бизнесе. Если первая заявка была оставлена до периода отчета, то все новые заявки клиента в периоде отчета будут повторными.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 3260,
		'type': 'percent',
		'formula': '({leads}) ? ({repeated_leads} * 100 / {leads}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeated_sales',
		'title': 'Повторные продажи',
		'info': 'Количество продаж клиентов, которые уже ранее совершали сделку в вашем бизнесе. Если первая заявка была оставлена до периода отчета, то все новые продажи клиента в периоде отчета будут повторными.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3290,
		'type': 'integer',
		'formula': '{repeated_sales} ? ({repeated_sales}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeated_sales_rate',
		'title': 'Повторные продажи, %',
		'info': 'Доля повторных продаж\nПовторные продажи / Продажи * 100%',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 3310,
		'type': 'percent',
		'formula': '({sales}) ? ({repeated_sales} * 100 / {sales}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeated_sales_revenue',
		'title': 'Выручка повторных продаж',
		'info': 'Выручка по продажам от текущих клиентов.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3340,
		'type': 'money',
		'formula': '{repeated_sales_revenue} ? ({repeated_sales_revenue}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeated_sales_profit',
		'title': 'Прибыль повторных продаж',
		'info': 'Прибыль по продажам от текущих клиентов.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3370,
		'type': 'money',
		'formula': '{repeated_sales_net_cost}\n                        ? ( {repeated_sales_revenue} - {repeated_sales_net_cost} )\n                        : ( {repeated_sales_revenue} * {$profitFactor} )',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'new_sales',
		'title': 'Новые продажи',
		'info': 'Продажи клиентов, которые ранее не оставляли сделок в вашем бизнесе.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3400,
		'type': 'integer',
		'formula': '{new_sales} ? ({new_sales}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'first_sales_revenue',
		'title': 'Выручка новых продаж',
		'info': 'Выручка по продажам от новых клиентов.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3430,
		'type': 'money',
		'formula': '{first_sales_revenue} ? ({first_sales_revenue}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'first_sales_profit',
		'title': 'Прибыль новых продаж',
		'info': 'Прибыль по продажам от новых клиентов.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3500,
		'type': 'money',
		'formula': '{first_sales_net_cost}\n                        ? ( {first_sales_revenue} - {first_sales_net_cost} )\n                        : ( {first_sales_revenue} * {$profitFactor} )',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_first_leads_revenue',
		'title': 'Потенциальная выручка новых заявок',
		'info': 'Потенциальная выручка от заявок со статусом «В работе» от новых клиентов.',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3600,
		'type': 'money',
		'formula': '{first_leads_revenue_in_progress} ? {first_leads_revenue_in_progress} : ({sales} ? {revenue}*{first_leads_in_progress}/{sales} : 0)',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'impressions',
		'title': 'Показы',
		'info': 'Количество показов рекламных объявлений',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 98,
		'type': 'integer',
		'formula': '{impressions} ? {impressions} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'ctr',
		'title': 'CTR',
		'info': 'Показатель кликабельности объявлений\nВизиты / Показы * 100%',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 99,
		'type': 'percent',
		'formula': '{impressions} ? (100 * {visits} / {impressions}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'visits',
		'title': 'Визиты',
		'info': 'Количество посещений сайта с уникальным рекламным источником',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 100,
		'type': 'integer',
		'formula': '{visits} ? {visits} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'unique_visits',
		'title': 'Уникальные посетители',
		'info': 'Количество уникальных посетителей сайта',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 110,
		'type': 'integer',
		'formula': '{unique_visits} ? {unique_visits} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'bounced_visits',
		'title': 'Отказные визиты',
		'info': 'Количество рекламных визитов пользователей, которые покинули сайт вскоре после захода, не выполнив никаких действий на нём.',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 125,
		'type': 'integer',
		'formula': '{bounced_visits} ? {bounced_visits} : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'bounce_rate',
		'title': 'Показатель отказов',
		'info': 'Доля отказов в общем количестве визитов',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 126,
		'type': 'percent',
		'formula': '{visits} ? (100 * {bounced_visits} / {visits}) : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'conversion_visits_to_leads',
		'title': 'Конверсия в заявки',
		'info': 'Доля заявок от общего числа визитов\nЗаявки / Визиты * 100%',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 150,
		'type': 'percent',
		'formula': '{visits} ? (100*{leads}/{visits}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'leads',
		'title': 'Заявки',
		'info': 'Заявки (лиды) — это любые обращения, поступившие в ваш бизнес. Например: заявки, отправленные из формы на сайте, созданные по звонкам или диалогам онлайн консультантов и т.п.',
		'group': 'orders',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 200,
		'type': 'integer',
		'formula': '{leads} ? {leads} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'conversion_leads_to_sales',
		'title': 'Конверсия в продажи',
		'info': 'Доля продаж от общего числа заявок\nПродажи / Заявки * 100%',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 300,
		'type': 'percent',
		'formula': '{leads} ? (100*{sales}/{leads}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'sales',
		'title': 'Продажи',
		'info': 'Заявки со статусом «Оплаченные»',
		'group': 'orders',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 400,
		'type': 'integer',
		'formula': '{sales} ? {sales} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'leads_in_progress',
		'title': 'Потенциальные продажи',
		'info': 'Заявки со статусом «В работе»',
		'group': 'orders',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 2100,
		'type': 'integer',
		'formula': '{leads_in_progress} ? {leads_in_progress} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'conversion_visits_to_sales',
		'title': 'Абсолютная конверсия',
		'info': 'Доля продаж от общего числа визитов\nПродажи / Визиты * 100%',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 600,
		'type': 'percent',
		'formula': '{visits} ? (100*{sales}/{visits}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_sales',
		'title': 'Прогнозируемые продажи',
		'info': 'Заявки со статусами «Оплаченные» и «В работе»',
		'group': 'orders',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 2600,
		'type': 'integer',
		'formula': '{sales}+{leads_in_progress}',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'canceled_leads',
		'title': 'Отмененные заявки',
		'info': 'Заявки со статусом «Отменённые»',
		'group': 'orders',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 2300,
		'type': 'integer',
		'formula': '{canceled_leads} ? {canceled_leads} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'revenue_in_progress',
		'title': 'Потенциальная выручка',
		'info': 'Потенциальная выручка от заявок со статусом «В работе»',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 2200,
		'type': 'money',
		'formula': '{revenue_in_progress} ? {revenue_in_progress} : ({sales} ? {revenue}*{leads_in_progress}/{sales} : 0)',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'revenue',
		'title': 'Выручка',
		'info': 'Выручка по заявкам со статусами «Оплаченные»',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 700,
		'type': 'money',
		'formula': '{revenue} ? {revenue} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_revenue',
		'title': 'Прогнозируемая выручка',
		'info': 'Выручка по заявкам со статусами «Оплаченные» и в «В работе»',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 2700,
		'type': 'money',
		'formula': '({revenue}?{revenue}:0)+({revenue_in_progress} ? {revenue_in_progress} : ({sales} ? {revenue}*{leads_in_progress}/{sales} : 0))',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'revenue_canceled',
		'title': 'Выручка отмененных заявок',
		'info': 'Выручка по заявкам со статусами «Отмененные»',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 2750,
		'type': 'money',
		'formula': '{revenue_canceled} ? {revenue_canceled} : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'net_cost',
		'title': 'Себестоимость',
		'info': 'Себестоимость заявки можно установить в разделе «Настройки» или импортировать из CRM',
		'group': 'cost',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 1000,
		'type': 'money',
		'formula': '{net_cost}',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'profit',
		'title': 'Прибыль',
		'info': 'Разница между Выручкой и Себестоимостью\nВыручка - Себестомость',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 1100,
		'type': 'money',
		'formula': '{net_cost}\n                    ? ( {revenue} - {net_cost} )\n                    : ( {revenue} * {$profitFactor} )',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_profit',
		'title': 'Прогнозируемая прибыль',
		'info': 'Максимально возможная прибыль по заявкам со статусами «Оплаченные» и «В работе»',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 2800,
		'type': 'money',
		'formula': '( ({revenue} ? {revenue} : 0)\n                        + ({revenue_in_progress} ? {revenue_in_progress} : ({sales} ? {revenue}*{leads_in_progress}/{sales} : 0))\n                        - {net_cost} )',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'average_sale',
		'title': 'Средний чек',
		'info': 'Средняя сумма продажи\nВыручка / Продажи',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 800,
		'type': 'money',
		'formula': '{sales}?{revenue}/{sales}:0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_average_sale',
		'title': 'Прогнозируемый средний чек',
		'info': 'Средняя сумма продажи с учётом потенциальных продаж\nПрогнозируемая выручка / Прогнозируемые продажи',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 2900,
		'type': 'money',
		'formula': '({leads_in_progress}+{sales})\n                    ?({revenue}+({revenue_in_progress} ? {revenue_in_progress} : ({sales} ? {revenue}*{leads_in_progress}/{sales} : 0)))/({leads_in_progress}+{sales})\n                    :0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'average_profit',
		'title': 'Средняя прибыль',
		'info': 'Средняя прибыль от одной продажи\nПрибыль / Продажи',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 900,
		'type': 'money',
		'formula': '{sales}\n                    ? ( \n                        ( {net_cost}\n                            ? ( {revenue} - {net_cost} )\n                            : ( {revenue} * {$profitFactor} )\n                        ) / {sales} )\n                    : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'marketing_cost',
		'title': 'Расходы',
		'info': 'Маркетинговые расходы',
		'group': 'cost',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 1300,
		'type': 'money',
		'formula': '{marketing_cost} ? {marketing_cost} : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'cpo',
		'title': 'CPO',
		'info': 'Средняя стоимость привлечения оплаченной заявки\nРасходы / Продажи',
		'group': 'cost',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 1900,
		'type': 'money',
		'formula': '{marketing_cost} ? ({sales}?{marketing_cost}/{sales}:0) : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'roi',
		'title': 'ROI',
		'info': 'Возврат инвестиций\n(Прибыль - Расходы) / Расходы * 100%',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 1400,
		'type': 'percent',
		'formula': '{marketing_cost} \n                    ? ( 100 * ( \n                        ( {net_cost} \n                            ? ( {revenue} - {net_cost} ) \n                            : ( {revenue} * {$profitFactor} )\n                        ) - {marketing_cost} ) / {marketing_cost}) \n                    : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'romi',
		'title': 'ROMI',
		'info': 'Возврат инвестиций без учёта себестоимости\n(Выручка - Расходы) / Расходы * 100%',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 1500,
		'type': 'percent',
		'formula': '{marketing_cost} ? (100 * ({revenue} - {marketing_cost})/{marketing_cost}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_roi',
		'title': 'Прогнозируемый ROI',
		'info': 'Возврат инвестиций с учётом заявок со статусами «Оплаченные» и «В работе»\n(Прогнозируемая прибыль - Расходы) / Расходы * 100%',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 2500,
		'type': 'percent',
		'formula': '{marketing_cost}\n                    ? (100*(\n                        ({net_cost}\n                            ? ({revenue}+({revenue_in_progress} ? {revenue_in_progress} : ({sales} ? {revenue}*{leads_in_progress}/{sales} : 0))-{net_cost})\n                            : (({revenue}+({revenue_in_progress} ? {revenue_in_progress} : ({sales} ? {revenue}*{leads_in_progress}/{sales} : 0)))*{$profitFactor})\n                        )\n                        -{marketing_cost})\n                        /{marketing_cost})\n                    : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'cpc',
		'title': 'CPC',
		'info': 'Средняя стоимость визита\nРасходы / Визиты',
		'group': 'cost',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 1700,
		'type': 'money',
		'formula': '{visits} ? {marketing_cost}/{visits} : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'cpl',
		'title': 'CPL',
		'info': 'Средняя стоимость заявки\nРасходы / Заявки',
		'group': 'cost',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 1800,
		'type': 'money',
		'formula': '{leads} ? {marketing_cost}/{leads} : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'net_profit',
		'title': 'Чистая прибыль',
		'info': 'Разница между Прибылью и Расходами\nПрибыль - Расходы',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 1200,
		'type': 'money',
		'formula': '({net_cost}\n                    ? ( {revenue} - {net_cost} )\n                    : ( {revenue} * {$profitFactor}) ) - {marketing_cost}',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'clients',
		'title': 'Клиенты',
		'info': 'Количество клиентов',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3000,
		'type': 'integer',
		'formula': '{clients} ? {clients} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'cac',
		'title': 'CAC',
		'info': 'Средняя стоимость привлечения оплатившего клиента\nРасходы / Оплатившие клиенты',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 3600,
		'type': 'money',
		'formula': '{paid_clients} ? ({marketing_cost} / {paid_clients}) : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'ltv',
		'title': 'LTV',
		'info': 'Средняя прибыль от плативших клиентов\nПрибыль / Оплатившие клиенты',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 3700,
		'type': 'money',
		'formula': '{paid_clients} ? (\n                    ({net_cost}\n                        ? ( {revenue} - {net_cost} )\n                        : ( {revenue} * {$profitFactor} ))\n                    / {paid_clients}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'paid_clients',
		'title': 'Оплатившие клиенты',
		'info': 'Учитываются уникальные клиенты в рамках календарного месяца. Если отчет строится за несколько месяцев, один и тот же клиент будет учтен несколько раз',
		'group': 'client',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3100,
		'type': 'integer',
		'formula': '{paid_clients} ? {paid_clients} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'marketing_cost_rate',
		'title': 'ДРР, %',
		'info': 'Доля рекламного расхода в прибыли\nРасходы / Прибыль * 100%',
		'group': 'cost',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 1600,
		'type': 'percent',
		'formula': '{net_cost}\n                    ? ( (({revenue} - {net_cost}) > 0 || ({revenue} - {net_cost}) < 0)\n                        ? {marketing_cost} / ({revenue} - {net_cost}) * 100\n                        : 0)\n                    : ({revenue}\n                        ? {marketing_cost} / ({revenue} * {$profitFactor}) * 100\n                        : 0)',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_cpo',
		'title': 'Прогнозируемый CPO',
		'info': 'Средняя стоимость привлечения заявок со статусами «Оплаченные» и «В работе»\nРасходы / Прогнозируемые продажи',
		'group': 'cost',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 2400,
		'type': 'money',
		'formula': '{marketing_cost} && ({sales} || {leads_in_progress})\n                    ? ({marketing_cost}) / ({sales}+{leads_in_progress})\n                    : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'marginality_rate',
		'title': 'Маржинальность, %',
		'info': 'Доля прибыли от выручки\nПрибыль / Выручка * 100%',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 2000,
		'type': 'percent',
		'formula': '{revenue}\n                    ? ({net_cost}\n                        ? (({revenue} - {net_cost}) / {revenue} * 100)\n                        : {$profitFactor} * 100 \n                      )\n                    : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'potential_net_profit',
		'title': 'Прогнозируемая чистая прибыль',
		'info': 'Разница между Прогнозируемой прибылью и Расходами',
		'group': 'profit',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 3800,
		'type': 'money',
		'formula': '( ({revenue} ? {revenue} : 0)\n                        + ({revenue_in_progress} ? {revenue_in_progress} : ({sales} ? {revenue}*{leads_in_progress}/{sales} : 0))\n                        - {net_cost} )\n                 - {marketing_cost}',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'conversion_leads_to_canceled_leads',
		'title': 'Конверсия в отмененные заявки',
		'info': 'Доля отмененных заявок от общего числа заявок\nОтмененные заявки / Заявки * 100%',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 3900,
		'type': 'percent',
		'formula': '{leads} ? (({leads} - {leads_in_progress} - {sales}) / {leads} * 100) : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'conversion_visits_to_canceled_leads',
		'title': 'Абсолютная конверсия в отмененные заявки',
		'info': 'Доля отмененных заявок от общего числа визитов\nОтмененные заявки / Визиты * 100%',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 3910,
		'type': 'percent',
		'formula': '{visits} ? (({leads} - {leads_in_progress} - {sales}) / {visits} * 100) : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'conversion_visits_to_potential_sales',
		'title': 'Конверсия в прогнозируемые продажи',
		'info': 'Доля прогнозируемых продаж от общего числа визитов. Прогнозируемые продажи / Визиты * 100%',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 3920,
		'type': 'percent',
		'formula': '{visits} ? (({sales} + {leads_in_progress}) / {visits} * 100) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'earnings_per_click',
		'title': 'EPC',
		'info': 'Средний доход с визита\nВыручка / Визиты',
		'group': 'profit',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 810,
		'type': 'money',
		'formula': '{visits} ? ({revenue} / {visits}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'mc_leads',
		'title': 'Мультиканальные заявки',
		'info': 'Количество заявок, в которых было задействовано несколько рекламных каналов',
		'group': 'orders',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 2340,
		'type': 'integer',
		'formula': '{mc_leads} ? {mc_leads} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'mc_leads_rate',
		'title': 'Мультиканальные заявки, %',
		'info': 'Доля мультиканальных заявок от общего количества заявок',
		'group': 'orders',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 2370,
		'type': 'percent',
		'formula': '{leads} ? ({mc_leads} ? (100*{mc_leads}/{leads}) : 0) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'ab_profit',
		'title': 'Прибыль варианта',
		'info': 'Прибыль, нормированная по наименее прибыльному варианту',
		'group': 'abTests',
		'is_has_attribution_model': True,
		'is_absolute': True,
		'order': 4100,
		'type': 'money',
		'formula': '{ab_profit_minimum}\n                        ? ({net_cost}\n                            ? ( {revenue} - {net_cost} )\n                            : ( {revenue} * {$profitFactor} )\n                         ) - {ab_profit_minimum}\n                        : 0',
		'is_complex': True,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'cba',
		'title': 'CBA',
		'info': 'Вероятность варианта победить остальные варианты, основанная на конверсии в заявки',
		'group': 'abTests',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 4200,
		'type': 'percent',
		'formula': '{chance_to_beat_all_sum_by_leads} ? {chance_to_beat_all_by_leads} / {chance_to_beat_all_sum_by_leads} * 100 : 0',
		'is_complex': True,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'cba+',
		'title': 'CBA+',
		'info': 'Вероятность варианта победить остальные варианты, основанная на прибыли',
		'group': 'abTests',
		'is_has_attribution_model': True,
		'is_absolute': False,
		'order': 4300,
		'type': 'percent',
		'formula': '{chance_to_beat_all_sum_by_sales} ? {chance_to_beat_all_by_sales} / {chance_to_beat_all_sum_by_sales} * 100 : 0',
		'is_complex': True,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'average_pay_time',
		'title': 'Средний цикл сделки',
		'info': 'Сумма времени прошедшего от создания сделок до оплаты / количество сделок',
		'group': 'orders',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 2400,
		'type': 'integer',
		'formula': '{sales_with_paid_date} ? ({payment_interval_sum} / {sales_with_paid_date} / 86400) : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'events',
		'title': 'Всего событий',
		'info': 'Метрика суммирует срабатывания за период всех событий, настроенных в проекте',
		'group': 'events',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4100,
		'type': 'integer',
		'formula': '{events} ? {events} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'events_unique',
		'title': 'Всего событий (с уникальным пользователем)',
		'info': 'Метрика суммирует события за период, у которых уникальный номер визита',
		'group': 'events',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4200,
		'type': 'integer',
		'formula': '{events_unique} ? {events_unique} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'date_events',
		'title': 'Всего событий (по дате события)',
		'info': 'Метрика суммирует срабатывания за период всех событий, настроенных в проекте',
		'group': 'eventsDate',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4100,
		'type': 'integer',
		'formula': '{date_events} ? {date_events} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'date_events_unique',
		'title': 'Всего событий (с уникальным пользователем) (по дате события)',
		'info': 'Метрика суммирует события за период, у которых уникальный номер визита',
		'group': 'eventsDate',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4200,
		'type': 'integer',
		'formula': '{date_events_unique} ? {date_events_unique} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'calls',
		'title': 'Звонки',
		'info': 'Общее количество звонков',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4100,
		'type': 'integer',
		'formula': '{calls} ? {calls} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'uniqueCalls',
		'title': 'Уникальные звонки',
		'info': 'Количество звонков с уникального номера телефона и источника',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4200,
		'type': 'integer',
		'formula': '{uniqueCalls} ? {uniqueCalls} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'uniquePhoneCalls',
		'title': 'Звонки с уникальных номеров',
		'info': 'Количество звонков с уникального номера телефона',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4200,
		'type': 'integer',
		'formula': '{uniquePhoneCalls} ? {uniquePhoneCalls} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'uniqueCallsShare',
		'title': 'Доля уникальных звонков',
		'info': 'Уникальные звонки / Звонки * 100%',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 4300,
		'type': 'percent',
		'formula': '{calls} ? ({uniqueCalls} / {calls} * 100) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeatedCalls',
		'title': 'Повторные звонки',
		'info': 'Количество звонков с номера телефона и источника, которые уже зафиксированы в проекте Roistat',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4350,
		'type': 'integer',
		'formula': '{calls} - {uniqueCalls}',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'repeatedCallsShare',
		'title': 'Доля повторных звонков',
		'info': 'Повторные звонки / Звонки * 100%',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 4360,
		'type': 'percent',
		'formula': '{calls} ? (({calls} - {uniqueCalls}) / {calls} * 100) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'callsConversion',
		'title': 'Конверсия в звонок',
		'info': 'Звонки / Визиты * 100%',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 4400,
		'type': 'percent',
		'formula': '{visits} ? ({calls} / {visits} * 100) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'callCost',
		'title': 'Стоимость привлеченного звонка',
		'info': 'Расходы / Уникальные звонки',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 4500,
		'type': 'money',
		'formula': '{uniqueCalls} ? {marketing_cost} / {uniqueCalls} : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'leadCallShare',
		'title': 'Доля звонков в заявках',
		'info': 'Звонки / Заявки * 100%',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 4600,
		'type': 'percent',
		'formula': '{leads} ? ({calls} / {leads} * 100) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'duration',
		'title': 'Среднее время разговора',
		'info': 'Продолжительность звонков / Звонки',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 4700,
		'type': 'duration',
		'formula': '{calls} ? {duration} / {calls} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'answeredCalls',
		'title': 'Отвеченные звонки',
		'info': 'Звонок считается отвеченным, если у него статус Отвечен (ANSWER)',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4800,
		'type': 'integer',
		'formula': '{answeredCalls} ? {answeredCalls} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'missedCalls',
		'title': 'Пропущенные звонки',
		'info': 'Звонок считается пропущенным, если у него статус отличен от Отвечен (ANSWER)',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4800,
		'type': 'integer',
		'formula': '{calls} - ({answeredCalls} ? {answeredCalls} : 0)',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'missedCallsShare',
		'title': 'Доля пропущенных звонков',
		'info': 'Пропущенные звонки / Звонки * 100%',
		'group': 'calltracking',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 4900,
		'type': 'percent',
		'formula': '{calls} \n                    ? ( ({calls} - ({answeredCalls} ? {answeredCalls} : 0) ) / {calls} * 100)\n                    : 0',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_sales',
		'title': 'Продажи',
		'info': 'Заявки со статусом «Оплаченные»',
		'group': 'payment',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 400,
		'type': 'integer',
		'formula': '{payment_sales} ? {payment_sales} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_revenue',
		'title': 'Выручка',
		'info': 'Выручка по заявкам со статусами «Оплаченные»',
		'group': 'payment',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 700,
		'type': 'money',
		'formula': '{payment_revenue} ? {payment_revenue} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_average_revenue',
		'title': 'Средний чек',
		'info': 'Средняя сумма продажи\nВыручка / Продажи',
		'group': 'payment',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 800,
		'type': 'money',
		'formula': '{payment_sales} ? ({payment_revenue} / {payment_sales}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_net_cost',
		'title': 'Себестоимость',
		'info': 'Себестоимость заявки можно установить в разделе «Настройки» или импортировать из CRM',
		'group': 'payment',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 1000,
		'type': 'money',
		'formula': '{payment_net_cost}\n                    ? {payment_net_cost}\n                    : ( {payment_revenue} * (1 - ({$profitFactor} ? {$profitFactor} : 1)) )',
		'is_complex': False,
		'is_inverted': True,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_profit',
		'title': 'Прибыль',
		'info': 'Разница между Выручкой и Себестоимостью\nВыручка - Себестомость',
		'group': 'payment',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 1200,
		'type': 'money',
		'formula': '{payment_net_cost}\n                    ? ( {payment_revenue} - {payment_net_cost} )\n                    : ( {payment_revenue} * {$profitFactor} )',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_marginality_rate',
		'title': 'Маржинальность, %',
		'info': 'Доля прибыли от выручки\nПрибыль / Выручка * 100%',
		'group': 'payment',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 2000,
		'type': 'percent',
		'formula': '{payment_net_cost}\n                    ? ({payment_net_cost}\n                        ? (({payment_revenue} - {payment_net_cost}) / {payment_revenue} * 100)\n                        : {$profitFactor} * 100 \n                      )\n                    : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_average_profit',
		'title': 'Средняя прибыль',
		'info': 'Средняя прибыль от одной продажи\nПрибыль / Продажи',
		'group': 'payment',
		'is_has_attribution_model': False,
		'is_absolute': False,
		'order': 2200,
		'type': 'money',
		'formula': '{payment_sales}\n                    ? (({payment_net_cost}\n                        ? ({payment_revenue} - {payment_net_cost})\n                        : ({payment_revenue} * {$profitFactor})) / {payment_sales})\n                        : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_quantity_total',
		'title': 'Товаров всего',
		'info': 'Количество единиц товара в сделках во всех статусах',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3500,
		'type': 'integer',
		'formula': '{products_quantity_total} ? {products_quantity_total} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_quantity_in_progress',
		'title': 'Товаров в работе',
		'info': 'Количество единиц товара в сделках, которые находятся в статусе «В работе»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3505,
		'type': 'integer',
		'formula': '{products_quantity_in_progress} ? {products_quantity_in_progress} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_quantity',
		'title': 'Товаров куплено',
		'info': 'Количество единиц товара в сделках, которые находятся в статусе «Оплачено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3510,
		'type': 'integer',
		'formula': '{products_quantity} ? {products_quantity} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_quantity_canceled',
		'title': 'Товаров отменено',
		'info': 'Количество единиц товара в сделках, которые находятся в статусе «Отменено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3515,
		'type': 'integer',
		'formula': '{products_quantity_canceled} ? {products_quantity_canceled} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_revenue_total',
		'title': 'Общая выручка по товарам',
		'info': 'Выручка по товарам в сделках во всех статусах',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3520,
		'type': 'money',
		'formula': '{products_revenue_total} ? {products_revenue_total} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_revenue_potential',
		'title': 'Потенциальная выручка по товарам',
		'info': 'Выручка по товарам в сделках, которые находятся в статусе «В работе»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3525,
		'type': 'money',
		'formula': '{products_revenue_potential} ? {products_revenue_potential} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_revenue',
		'title': 'Выручка по товарам',
		'info': 'Выручка по товарам в сделках, которые находятся в статусе «Оплачено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3530,
		'type': 'money',
		'formula': '{products_revenue} ? {products_revenue} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_revenue_canceled',
		'title': 'Недополученная выручка по товарам',
		'info': 'Выручка по товарам в сделках, которые находятся в статусе «Отменено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3535,
		'type': 'money',
		'formula': '{products_revenue_canceled} ? {products_revenue_canceled} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_profit_total',
		'title': 'Общая прибыль по товарам',
		'info': 'Прибыль по товарам в сделках во всех статусах',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3540,
		'type': 'money',
		'formula': '{products_profit_total} ? {products_profit_total} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_profit_potential',
		'title': 'Потенциальная прибыль по товарам',
		'info': 'Прибыль по товарам в сделках, которые находятся в статусе «В работе»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3545,
		'type': 'money',
		'formula': '{products_profit_potential} ? {products_profit_potential} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_profit',
		'title': 'Прибыль по товарам',
		'info': 'Прибыль по товарам в сделках, которые находятся в статусе «Оплачено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3550,
		'type': 'money',
		'formula': '{products_profit} ? {products_profit} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_profit_canceled',
		'title': 'Недополученная прибыль по товарам',
		'info': 'Прибыль по товарам в сделках, которые находятся в статусе «Отменено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3555,
		'type': 'money',
		'formula': '{products_profit_canceled} ? {products_profit_canceled} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_products_quantity',
		'title': 'Товаров куплено',
		'info': 'Количество единиц товара в сделках, которые находятся в статусе «Оплачено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3510,
		'type': 'integer',
		'formula': '{payment_products_quantity} ? {payment_products_quantity} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_products_revenue',
		'title': 'Выручка по товарам',
		'info': 'Выручка по товарам в сделках, которые находятся в статусе «Оплачено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3530,
		'type': 'money',
		'formula': '{payment_products_revenue} ? {payment_products_revenue} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'payment_products_profit',
		'title': 'Прибыль по товарам',
		'info': 'Прибыль по товарам в сделках, которые находятся в статусе «Оплачено»',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3550,
		'type': 'money',
		'formula': '{payment_products_profit} ? {payment_products_profit} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_marketing_cost',
		'title': 'Расходы на товары',
		'info': 'Маркетинговые расходы на товары',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3560,
		'type': 'money',
		'formula': '{products_marketing_cost} ? {products_marketing_cost} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_view',
		'title': 'Просмотры по товарам',
		'info': 'Количество просмотров страницы товара',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3565,
		'type': 'integer',
		'formula': '{products_view} ? {products_view} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'products_roi',
		'title': 'ROI по товарам',
		'info': 'Коэффициент возврата инвестиций.\n(Прибыль по товарам - Расходы на товары) / Расходы на товары × 100%',
		'group': 'order_products',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 3570,
		'type': 'percent',
		'formula': '{products_marketing_cost} ? (100 * ({products_marketing_profit} - {products_marketing_cost}) / {products_marketing_cost}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'unique_contacts',
		'title': 'Уникальные контакты',
		'info': 'Количество уникальных пользователей, совершивших контакт по объявлению. Контактом может быть запрос телефона продавца, начало чата с продавцом, отклик на резюме',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4200,
		'type': 'integer',
		'formula': '{unique_contacts} ? {unique_contacts} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'favorites',
		'title': 'Добавления в избранное',
		'info': 'Количество уникальных пользователей, добавивших объявление в избранное',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4210,
		'type': 'integer',
		'formula': '{favorites} ? {favorites} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'clicks',
		'title': 'Клики',
		'info': 'Количество кликов',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 4220,
		'type': 'integer',
		'formula': '{clicks} ? {clicks} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'online_chats',
		'title': 'Чаты',
		'info': 'Количество чатов, имеющих хотя бы одно сообщение',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 5000,
		'type': 'integer',
		'formula': '{online_chats} ? {online_chats} : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	},
	{
		'name': 'conversion_visits_to_online_chats',
		'title': 'Конверсия в чат',
		'info': 'Чаты / Визиты',
		'group': 'visitsAndConversions',
		'is_has_attribution_model': False,
		'is_absolute': True,
		'order': 5100,
		'type': 'percent',
		'formula': '{visits} ? (100*{online_chats}/{visits}) : 0',
		'is_complex': False,
		'is_inverted': False,
		'is_available': True,
		'extended_formula': None
	}],
	'status': 'success'
}
"""